version: "2"

services:
    traefik:
        image: traefik
        container_name: traefik
        command: --web 
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./config/traefik/traefik.toml:/traefik.toml:ro"
            - "./config/traefik/rules.toml:/rules.toml:ro"
            - "./config/traefik/letsencrypt.json:/letsencrypt.json"
            - "./data/traefik/acme:/etc/traefik/acme"
        networks:
            - reverse-proxy

networks:
    reverse-proxy:
        external: true

