version: '2'

services:
    code:
        image: eraac/xxx
        volumes:
            - "./config/code/parameters.yml:/var/www/app/config/parameters.yml:ro"
            - "./logs/code:/var/www/var/logs"

    php:
        image: eraac/php:7 # php:7-dev also available
        expose:
            - "9000"
        links:
            - code
        external_links:
            - mysql
            - fake-smtp
        volumes_from:
            - code
        networks:
            - fake-smtp
            - mysql
            - default
        labels:
            - "traefik.enable=false"

    nginx:
        image: eraac/nginx
        labels:
            - "traefik.backend=app-name"
            - "traefik.frontend.rule=Host:domain.tld"
            - "traefik.port=80"
            - "traefik.docker.network=reverse-proxy"
            - "traefik.enable=true"
        links:
            - php
            - code
        volumes:
            - "./logs/nginx/:/var/log/nginx"
            - "./config/nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf:ro"
        volumes_from:
            - code
        networks:
            - reverse-proxy
            - default

networks:
    mysql:
        external: true
    fake-smtp:
        external: true
    reverse-proxy:
        external: true
