version: "2"

services:

  nginx:
    image: nginx
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/proxy/conf.d:/etc/nginx/conf.d"
      - "./config/proxy/vhost.d:/etc/nginx/vhost.d"
      - "./config/proxy/htpasswd:/etc/nginx/htpasswd"
      - "./config/proxy/html:/usr/share/nginx/html"
      - "./config/proxy/certs:/etc/nginx/certs:ro"
    networks:
      - reverse-proxy

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./config/proxygen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup reverse_proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory

networks:
  reverse-proxy:
    external: true

