version: '2'

services:
    mysql:
        image: mysql
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./config/mysql:/etc/mysql/conf.d:ro
        networks:
            - mysql

networks:
  mysql:
    external: true

